unpackaged/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>OpenStax College book offerings</description>
    <label>Book</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Book__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Active for marketing/website</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Annualization_number__c.field-meta.xml
<CustomField>
    <fullName>Annualization_number__c</fullName>
    <label>Annualization number</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <inlineHelpText>date</inlineHelpText>
    <label>Publish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Short_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Book_Name__c</fullName>
    <label>Short Book Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Tutor_Subject__c.field-meta.xml
<CustomField>
    <fullName>Tutor_Subject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tutor Subject</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Annualization_Number__c.field-meta.xml
<CustomField>
    <fullName>Annualization_Number__c</fullName>
    <formula>Book__r.Annualization_number__c-1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annualization Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Class_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Class_Start_Date__c</fullName>
    <label>Class Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Short_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Book_Name__c</fullName>
    <formula>Book__r.Short_Book_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Short Book Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Students__c.field-meta.xml
<CustomField>
    <fullName>Students__c</fullName>
    <label>Students</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Time_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Period__c</fullName>
    <label>Time Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semester</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/Tutor_Course__c.object-meta.xml
<CustomObject>
    <label>Tutor Course Section</label>
    <nameField>
        <label>Tutor Course Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tutor Course Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tutor_Course__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Book__c.Tutor_Subject__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Tutor Course Sections</relationshipLabel>
    <relationshipName>Tutor_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/fields/Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Book_Name__c</fullName>
    <description>From Tutor</description>
    <label>Book Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/fields/Class_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Class_Start_Date__c</fullName>
    <formula>CASE( TEXT(Term__c) , 
"Fall", Opportunity__r.Fall_Start_Date__c , 
"Spring",  Opportunity__r.Spring_Start_Date__c ,
 Opportunity__r.Class_Start_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Class Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>From Tutor (if possible)</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Tutor_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/fields/External_UUID__c.field-meta.xml
<CustomField>
    <fullName>External_UUID__c</fullName>
    <description>From Tutor</description>
    <label>External UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/fields/Main_Course__c.field-meta.xml
<CustomField>
    <fullName>Main_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Course</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Tutor_Course__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Tutor_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TutorCourseAssigning_Test.cls
@isTest
public class TutorCourseAssigning_Test {
    public static String CRON_EXP = '0 0 0 15 3 ? 2027';
    public static TestMethod void testthethings(){
        
        Account a = new Account();
        a.Name = 'test account';
        insert a;
        
        Contact c = new Contact();
        c.LastName = 'test contact';
        c.AccountId = a.id;
        insert c;
        
        Book__c book 					= new Book__c();
        book.Name    					= 'Biology';
        book.Short_Book_Name__c 		= 'Bio';
        book.Annualization_number__c 	= 1.6;
        book.Active__c					= TRUE;
        book.Publish_Date__c			= DATE.TODAY()-5;
        book.Tutor_Subject__c			= TRUE;
        
        insert book; 
        
        Opportunity o = new Opportunity();        
        o.Name					= 'Opp';
        o.Contact__c			= c.Id;
        o.AccountId				= a.Id;
        o.Book__c				= book.Id;
        o.Class_Start_Date__c	= date.newInstance(date.today().year()+(date.today().month() > 6 ? 2:1),01,05);
        o.Students__c			= 10;
        o.StageName				= 'Confirmed Adoption Won';
        o.CloseDate				= Date.Today();
        o.Time_Period__c		= 'Semester';
        insert o;
        
        

        List<Tutor_Course__c> TCUP = new List<Tutor_Course__c>();
        
        Tutor_Course__c TC1 = new Tutor_Course__c();
        TC1.Name 				= 'TC1';
        TC1.External_UUID__c 	= '1';
        TC1.Opportunity__c 		= o.Id;
        TC1.Book__c				= book.Id;
        TC1.Book_Name__c		= book.Name;
        TC1.Contact__c 			= c.id;
        TC1.Main_Course__c 		= TRUE;
        TCUP.add(TC1);
        
        Tutor_Course__c TC2 = new Tutor_Course__c();
        TC2.Name 				= 'TC2';
        TC2.External_UUID__c 	= '2';
        TC2.Opportunity__c 		= o.Id;
        TC2.Book__c				= book.Id;
        TC2.Book_Name__c		= book.Name;
        TC2.Contact__c 			= c.id;
        TC2.Main_Course__c 		= FALSE;
        TCUP.add(TC2);

        Tutor_Course__c TC3 = new Tutor_Course__c();
        TC3.Name 				= 'TC3';
        TC3.External_UUID__c 	= '2';
        TC3.Opportunity__c 		= o.Id;
        TC3.Book__c				= book.Id;
        TC3.Book_Name__c		= book.Name;
        TC3.Contact__c 			= c.id;
        TC3.Main_Course__c 		= FALSE;
        TCUP.add(TC3);
        
        
        insert TCUP;
        
        Test.startTest();
        
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP, 
            new TutorCourseAssigning());
        
        Test.stopTest();
        //TutorCourseAssigning.SC();
        
        List<Tutor_Course__c> Mains = [SELECT ID, Main_Course__c
                                       FROM Tutor_Course__c
                                       WHERE Main_Course__c = TRUE];
        
        system.debug('Mains '+Mains);
        system.debug('Mains.size ' + Mains.size());
        system.assert(Mains.size() == 2);
        
    }
}