unpackaged/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>OpenStax College book offerings</description>
    <label>Book</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Book__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Active for marketing/website</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Annualization_number__c.field-meta.xml
<CustomField>
    <fullName>Annualization_number__c</fullName>
    <label>Annualization number</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <inlineHelpText>date</inlineHelpText>
    <label>Publish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Annualization_Number__c.field-meta.xml
<CustomField>
    <fullName>Annualization_Number__c</fullName>
    <formula>Book__r.Annualization_number__c-1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annualization Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Class_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Class_Start_Date__c</fullName>
    <label>Class Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Need_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Need_Rollup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Rollup</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Status__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Status__c</fullName>
    <label>Renewal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs Renewal</fullName>
                <default>true</default>
                <label>Needs Renewal</label>
            </value>
            <value>
                <fullName>Done Renewed</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>Needs check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Students__c.field-meta.xml
<CustomField>
    <fullName>Students__c</fullName>
    <label>Students</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Time_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Period__c</fullName>
    <label>Time Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semester</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BulkRollupTest.cls
@isTest
public class BulkRollupTest {
    public static TestMethod void rollovertest(){
        system.assert(true);
        
        Account a 		= new account();
        a.Name			= 'thisisatestuniveristy';
        a.Type			= 'College/University (4)';
        insert a;
        
        Contact c 		= new contact();
        c.FirstName		= 'Denver';
        c.LastName		= 'Test';
        c.AccountId 	= a.id;
        c.Email			= 'denver+test@rice.edu';
        c.Phone			= '0000000000';
        insert c;
        
        Book__c bookPsyc 	= new Book__c();
        bookPsyc.Name						= 'Psychology';
        bookPsyc.Active__c					= true;
        bookPsyc.Annualization_number__c 	= 1.6;
        bookPsyc.Publish_Date__c			= date.newInstance(2015, 03, 04);
        insert bookPsyc;
        
        Opportunity oppPrevious 		= new Opportunity();
        oppPrevious.Name				= 'temp name';
        oppPrevious.StageName			= 'Confirmed Adoption Won';
        oppPrevious.Contact__c			= c.id;
        oppPrevious.AccountId			= a.id;
        oppPrevious.Book__c				= bookPsyc.id;
        oppPrevious.Description			= 'temp';
        oppPrevious.Class_Start_Date__c = date.newInstance(2019, 08, 10);
        oppPrevious.Students__c			= 30;
        oppPrevious.Time_Period__c		= 'Year';
        oppPrevious.CloseDate			= date.today();
        oppPrevious.Renewal_Status__c	= 'Needs Renewal';
        oppPrevious.Need_Rollup__c		= TRUE;
        insert oppPrevious;
                
        
        test.startTest();
        BulkRollup BR = new BulkRollup();
        Database.executeBatch(BR,5);
        test.stopTest();
       
    }
}