unpackaged/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>OpenStax College book offerings</description>
    <label>Book</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Book__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Active for marketing/website</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Annualization_number__c.field-meta.xml
<CustomField>
    <fullName>Annualization_number__c</fullName>
    <label>Annualization number</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <inlineHelpText>date</inlineHelpText>
    <label>Publish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Short_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Book_Name__c</fullName>
    <label>Short Book Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Book__c/fields/Tutor_Subject__c.field-meta.xml
<CustomField>
    <fullName>Tutor_Subject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tutor Subject</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ReportedBookTest.cls
@isTest
public class ReportedBookTest {
    static testMethod void validateReportedbook(){
        Book__c book 					= new Book__c();
        book.Name    					= 'Biology';
        book.Short_Book_Name__c 		= 'Bio';
        book.Annualization_number__c 	= 1.6;
        book.Active__c					= TRUE;
        book.Publish_Date__c			= DATE.TODAY()-5;
        book.Tutor_Subject__c			= TRUE;
        
        insert book; 
        
        ReportedBook rBook = new ReportedBook();
        
        rBook.bookId = book.Id; 
        rBook.name = book.Name; 
        rBook.students = 13; 
        
        System.assertEquals(book.Id, rBook.bookId);
        System.assertEquals(book.name, rBook.name);
        System.assertEquals(13, rBook.students);
       
    }
}