unpackaged/main/default/objects/Account/fields/Books_Adopted__c.field-meta.xml
<CustomField>
    <fullName>Books_Adopted__c</fullName>
    <label>Books Adopted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Savings_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Savings_Current_Year__c</fullName>
    <inlineHelpText>Savings this year (school year).</inlineHelpText>
    <label>Savings Current Year</label>
    <summarizedField>Opportunity.Yearly_Savings__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Base_Year__c</field>
        <operation>equals</operation>
        <value>2022</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.IsWon</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Savings_Next_Year__c.field-meta.xml
<CustomField>
    <fullName>Savings_Next_Year__c</fullName>
    <inlineHelpText>Any savings for future adoptions (school year).</inlineHelpText>
    <label>Savings Next Year</label>
    <summarizedField>Opportunity.Yearly_Savings__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Base_Year__c</field>
        <operation>equals</operation>
        <value>2023</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.IsWon</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Savings_Past_Years__c.field-meta.xml
<CustomField>
    <fullName>Savings_Past_Years__c</fullName>
    <inlineHelpText>Not last year, but everything older savings (school year).</inlineHelpText>
    <label>Savings Past Years</label>
    <summarizedField>Opportunity.Yearly_Savings__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Base_Year__c</field>
        <operation>lessThan</operation>
        <value>2021</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.IsWon</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Savings_Previous_Year__c.field-meta.xml
<CustomField>
    <fullName>Savings_Previous_Year__c</fullName>
    <inlineHelpText>Savings last year (school year).</inlineHelpText>
    <label>Savings Previous Year</label>
    <summarizedField>Opportunity.Yearly_Savings__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Base_Year__c</field>
        <operation>equals</operation>
        <value>2021</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.IsWon</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>Colleges, Universities, High Schools</description>
    <label>School</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Books_Adopted__c.field-meta.xml
<CustomField>
    <fullName>Books_Adopted__c</fullName>
    <defaultValue>"None"</defaultValue>
    <description>Books being adopted. Populated from Automatic flow</description>
    <inlineHelpText>List of books adopted</inlineHelpText>
    <label>Books Adopted</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Current_Students__c.field-meta.xml
<CustomField>
    <fullName>Current_Students__c</fullName>
    <inlineHelpText>Students For current year (academic year).</inlineHelpText>
    <label>Current Year Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Fall_Students__c.field-meta.xml
<CustomField>
    <fullName>Fall_Students__c</fullName>
    <inlineHelpText>Fall students for current school year</inlineHelpText>
    <label>Current SY Fall Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Future_Students__c.field-meta.xml
<CustomField>
    <fullName>Future_Students__c</fullName>
    <inlineHelpText>Students For next year (academic year).</inlineHelpText>
    <label>Next Year Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Initial_Adoption_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Adoption_Date__c</fullName>
    <inlineHelpText>The date we first learned of their adoption</inlineHelpText>
    <label>Initial Adoption Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_of_Subjects__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Subjects__c</fullName>
    <inlineHelpText>Number of subjects contact is interested in</inlineHelpText>
    <label>Number of Subjects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Past_Students__c.field-meta.xml
<CustomField>
    <fullName>Past_Students__c</fullName>
    <inlineHelpText>Students For past year (academic year).</inlineHelpText>
    <label>Past Year Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Possible_Students_Year__c.field-meta.xml
<CustomField>
    <fullName>Possible_Students_Year__c</fullName>
    <inlineHelpText>Sum of opportunities, including Interest  (This year means academic year).</inlineHelpText>
    <label>Possible Students This Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Previous_Students__c.field-meta.xml
<CustomField>
    <fullName>Previous_Students__c</fullName>
    <inlineHelpText>Students For Past year (academic year).</inlineHelpText>
    <label>Previous Year Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>The date that they filled out a renewal form which got entered as a lead and then processed.</description>
    <inlineHelpText>The most recent date that someone has confirmed adoption</inlineHelpText>
    <label>Recent Adoption Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Savings_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Savings_Current_Year__c</fullName>
    <label>Savings Current Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Savings_Next_Year__c.field-meta.xml
<CustomField>
    <fullName>Savings_Next_Year__c</fullName>
    <label>Savings Next Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Savings_Past_Years__c.field-meta.xml
<CustomField>
    <fullName>Savings_Past_Years__c</fullName>
    <label>Savings Past Years</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Savings_Previous_Year__c.field-meta.xml
<CustomField>
    <fullName>Savings_Previous_Year__c</fullName>
    <label>Savings Previous Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Spring_Students__c.field-meta.xml
<CustomField>
    <fullName>Spring_Students__c</fullName>
    <inlineHelpText>Spring students for current school year</inlineHelpText>
    <label>Current SY Spring Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Base_Year__c.field-meta.xml
<CustomField>
    <fullName>Base_Year__c</fullName>
    <formula>year( Class_Start_Date__c )- 

IF(Month(Class_Start_Date__c) &gt;6, 
   0, 
   1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Book_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Book_Opportunity__c</fullName>
    <formula>OR(  RecordTypeId = "0120B000000NAH0", RecordTypeId = "0120B000000NAH5")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Book Opportunity</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Books_Adopted__c.field-meta.xml
<CustomField>
    <fullName>Books_Adopted__c</fullName>
    <formula>Contact__r.Books_Adopted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Books Adopted</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Department_Adoption__c.field-meta.xml
<CustomField>
    <fullName>Department_Adoption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Department Adoption</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Department_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Department_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Department opp is not a department</errorMessage>
        <filterItems>
            <field>Opportunity.Department_Adoption__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opps in Dept</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DeptSort__c.field-meta.xml
<CustomField>
    <fullName>DeptSort__c</fullName>
    <formula>IF(  Opportunity_Record_Type_Name__c = "Tutor Opp", "",

 Book__c  
&amp;
 CASESAFEID( Account.Id )
&amp;
 TEXT(Base_Year__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DeptSort</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fall_Dept_Max_Students__c.field-meta.xml
<CustomField>
    <fullName>Fall_Dept_Max_Students__c</fullName>
    <label>Fall Dept Max Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fall_Students__c.field-meta.xml
<CustomField>
    <fullName>Fall_Students__c</fullName>
    <label>Fall Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Need_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Need_Rollup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Rollup</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type_Name__c</fullName>
    <description>Record Type Name</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Record Type Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/sort__c.field-meta.xml
<CustomField>
    <fullName>sort__c</fullName>
    <description>Used for sorting opps by duplicates when exported to csv</description>
    <formula>IF(RecordType.Name = "Tutor Opp","T","")&amp;
Book__r.Id &amp; 
AccountId &amp; 
Contact_ID__c &amp; 
IF(Department_Adoption__c,"TRUE","FALS") &amp; 
TEXT(Base_Year__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>sort</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Spring_Dept_Max_Students__c.field-meta.xml
<CustomField>
    <fullName>Spring_Dept_Max_Students__c</fullName>
    <label>Spring Dept Max Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Spring_Students__c.field-meta.xml
<CustomField>
    <fullName>Spring_Students__c</fullName>
    <label>Spring Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Students__c.field-meta.xml
<CustomField>
    <fullName>Students__c</fullName>
    <label>Students</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Summer_Dept_Max_Students__c.field-meta.xml
<CustomField>
    <fullName>Summer_Dept_Max_Students__c</fullName>
    <label>Summer Dept Max Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Summer_Students__c.field-meta.xml
<CustomField>
    <fullName>Summer_Students__c</fullName>
    <label>Summer Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Trigger_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Rollup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>bulk processing</description>
    <label>Trigger Rollup</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Yearly_Savings__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Savings__c</fullName>
    <formula>Yearly_Students__c * Saving_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Yearly_Students__c * Saving_Number__c</inlineHelpText>
    <label>Yearly Savings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Yearly_Students__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Students__c</fullName>
    <formula>Fall_Students__c + Spring_Students__c + Summer_Students__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Fall_Students__c + Spring_Students__c + Summer_Students__c</inlineHelpText>
    <label>Yearly Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/OppRollup.cls
global class OppRollup implements Database.Batchable<SObject> {
    
    global Iterable<SObject> start(Database.BatchableContext bc) {
        //System.debug('define query');
        Datetime oneWeekAgo = System.today()-7;
        
        List<Opportunity> opps = [SELECT Id, Need_Rollup__c, Trigger_Rollup__c, Contact__c, Yearly_Students__c, Description,
            Yearly_Savings__c, Department_Adoption__c, Department_Opportunity__c, Book_Opportunity__c,
            sort__c, DeptSort__c, AccountId, Fall_Students__c, Spring_Students__c, Summer_Students__c,
            Fall_Dept_Max_Students__c, Spring_Dept_Max_Students__c, Summer_Dept_Max_Students__c
        FROM Opportunity
        WHERE Need_Rollup__c = TRUE
        AND LastModifiedDate > :oneWeekAgo //maybe use DateTime oneWeekAgo = System.Today()-7;
        AND Opportunity_Record_Type_Name__c = 'Book Opp'
        ORDER BY Contact__c
        ];
        //System.debug('Opps: '+opps);
        return opps;
    
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> opps){
        //System.debug('Execute');
        calculateRollup(opps);
    }
    
    @InvocableMethod
    global static void calculateRollup(List<Opportunity> opps){
        //System.debug('Start OppRollup');
        //System.debug('Opps: '+opps);
        
        //Make empty set to collect school IDs. Using a set because it cannot contain duplicates
        Set<Id> setContactID  = new Set<Id>();
        Set<Id> setAccountID = new Set<Id>();
        List<Opportunity> deptsNeedRollup = new List<Opportunity>();
        List<Opportunity> normalOppsUpdate = new List<Opportunity>();
        List<Opportunity> depts = new List<Opportunity>();
        
        //Loop through Opps and add to set
        for(Opportunity opp : opps){
            //system.debug('Opp: '+Opp);
            opp.Need_Rollup__c = false;
            opp.Trigger_Rollup__c = false;
            if(opp.Department_Adoption__c == false && !duplicateDeptOpportunity(opp, deptsNeedRollup)){
                //System.debug('Opp not duplicate: ' + opp);
                if (opp.Contact__c != null) {
                    setContactID.add(opp.Contact__c);
                }
                if (opp.AccountId != null) {
                    setAccountID.add(opp.AccountId);
                }
                if (opp.Department_Opportunity__c != null) {
                    Opportunity oppdept = new Opportunity();
                    oppdept.Id = opp.Department_Opportunity__c;
                    oppdept.Need_Rollup__c = true;
                    deptsNeedRollup.add(oppdept);
                }
                normalOppsUpdate.add(opp);
            }
            else{
                //System.debug('adding to depts: ' + opp);
                depts.add(opp);
            }
        }
        
        
        ///////////////////////////////////////////////////////Contacts
        if(setContactID.size()>0){
            //Get Map of objects, for easy updating
            Map<Id,Contact> mapContacts = new Map<Id,Contact> (
            [SELECT Id, Current_Students__c, Future_Students__c,
                Previous_Students__c, Past_Students__c,
                Fall_Students__c , Spring_Students__c,
                Number_of_Subjects__c, Books_Adopted__c,
                Initial_Adoption_Date__c, Renewal_Date__c,
                Savings_Current_Year__c , Savings_Next_Year__c,
                Savings_Past_Years__c, Savings_Previous_Year__c ,
                Possible_Students_Year__c
            FROM Contact WHERE Id IN :setContactID FOR UPDATE]);
            //System.debug('mapContacts: '+mapContacts);
            
            //Set Students to 0, so we can iterate and add
            for(Id idContact : mapContacts.keySet() ){
                mapContacts.get(idContact).Current_Students__c 		= 0 ;
                mapContacts.get(idContact).Future_Students__c 		= 0 ;
                mapContacts.get(idContact).Previous_Students__c 	= 0 ;
                mapContacts.get(idContact).Past_Students__c 		= 0 ;
                mapContacts.get(idContact).Fall_Students__c 		= 0 ;
                mapContacts.get(idContact).Spring_Students__c 		= 0 ;
                mapContacts.get(idContact).Number_of_Subjects__c	= 0 ;
                mapContacts.get(idContact).Savings_Current_Year__c	= 0 ;
                mapContacts.get(idContact).Savings_Next_Year__c		= 0 ;
                mapContacts.get(idContact).Savings_Past_Years__c	= 0 ;
                mapContacts.get(idContact).Savings_Previous_Year__c	= 0 ;
                mapContacts.get(idContact).Books_Adopted__c 		= null;
                mapContacts.get(idContact).Initial_Adoption_Date__c = null;//date.newInstance(2050,01,01);
                mapContacts.get(idContact).Renewal_Date__c 			= null;//date.newInstance(2000,01,01);
            }
            
            //Get list of Opportunities underneath the Contact OR Dept OR Adoption
            List<Opportunity> allOpps = [SELECT Id, Contact__c, Department_Adoption__c, Yearly_Students__c,
                AccountId , Base_Year__c, Fall_Students__c, Spring_Students__c, Book_Text__c,
                CloseDate , Department_Opportunity__c, Students__c, Class_Start_Date__c, Description,
                Yearly_Savings__c, IsWon, IsClosed, Opportunity_Record_Type_Name__c
            FROM Opportunity
            WHERE Contact__c IN :setContactID AND Department_Adoption__c = false
            LIMIT 10000];
            //System.debug('allOpps: '+ allOpps);
            
            //get current school year/term
            Integer baseyear = Date.today().year() - (Date.today().month() <7 ? 1 : 0);
            //System.debug('baseyear: '+baseyear);
            
            //Loop through allOpps, add student values
            for(Opportunity opp: allOpps){
                //System.debug('opp: '+opp);
                //Contacts
                if(opp.Opportunity_Record_Type_Name__c == 'Book Opp' && opp.IsWon == true){
                    mapContacts.get(opp.Contact__c).Future_Students__c 			+= (opp.Base_Year__c >  baseyear  ? opp.Yearly_Students__c : 0);
                    mapContacts.get(opp.Contact__c).Current_Students__c  		+= (opp.Base_Year__c == baseyear  ? opp.Yearly_Students__c : 0);
                    mapContacts.get(opp.Contact__c).Previous_Students__c 		+= (opp.Base_Year__c == baseyear-1? opp.Yearly_Students__c : 0);
                    mapContacts.get(opp.Contact__c).Past_Students__c  			+= (opp.Base_Year__c <  baseyear-1? opp.Yearly_Students__c : 0);
                    mapContacts.get(opp.Contact__c).Savings_Next_Year__c 		+= (opp.Base_Year__c >  baseyear  ? opp.Yearly_Savings__c  : 0);
                    mapContacts.get(opp.Contact__c).Savings_Current_Year__c 	+= (opp.Base_Year__c == baseyear  ? opp.Yearly_Savings__c  : 0);
                    mapContacts.get(opp.Contact__c).Savings_Previous_Year__c 	+= (opp.Base_Year__c == baseyear-1? opp.Yearly_Savings__c  : 0);
                    mapContacts.get(opp.Contact__c).Savings_Past_Years__c  		+= (opp.Base_Year__c <  baseyear-1? opp.Yearly_Savings__c  : 0);
                    if(opp.Base_Year__c == baseyear ){ // setting books adopted
                        //Change to use String.isBlank()
                        if(mapContacts.get(opp.Contact__c).Books_Adopted__c == null ){
                            mapContacts.get(opp.Contact__c).Books_Adopted__c = opp.Book_Text__c;
                        }
                        //combine statement with if above
                        else if ( !mapContacts.get(opp.Contact__c).Books_Adopted__c.contains(opp.Book_Text__c) ){
                            mapContacts.get(opp.Contact__c).Books_Adopted__c += ', ' + opp.Book_Text__c;
                        }
                    }
                    if(mapContacts.get(opp.Contact__c).Initial_Adoption_Date__c == null){
                        mapContacts.get(opp.Contact__c).Initial_Adoption_Date__c = opp.CloseDate;
                    }
                    else{
                        mapContacts.get(opp.Contact__c).Initial_Adoption_Date__c = (opp.CloseDate < mapContacts.get(opp.Contact__c).Initial_Adoption_Date__c ? opp.CloseDate : mapContacts.get(opp.Contact__c).Initial_Adoption_Date__c);
                    }
                    if(mapContacts.get(opp.Contact__c).Renewal_Date__c == null){
                        mapContacts.get(opp.Contact__c).Renewal_Date__c = opp.CloseDate;
                    }
                    else{
                        mapContacts.get(opp.Contact__c).Renewal_Date__c = (opp.CloseDate > mapContacts.get(opp.Contact__c).Renewal_Date__c ? opp.CloseDate : mapContacts.get(opp.Contact__c).Renewal_Date__c);
                    }
                    if(opp.Fall_Students__c != null){
                        mapContacts.get(opp.Contact__c).Fall_Students__c = mapContacts.get(opp.Contact__c).Fall_Students__c + (opp.Base_Year__c == baseyear  ? opp.Fall_Students__c : 0);
                    }
                    if(opp.Spring_Students__c != null){
                        mapContacts.get(opp.Contact__c).Spring_Students__c = mapContacts.get(opp.Contact__c).Spring_Students__c + (opp.Base_Year__c == baseyear  ? opp.Spring_Students__c : 0);
                    }
                }
                
                /*ELSE IF(Opp.Opportunity_Record_Type_Name__c == 'Tutor Opp'){
                    IF(Opp.IsWon == TRUE){
                        //Won Tutor Opp
                    }
                    ELSE IF(Opp.IsClosed == FALSE){
                        //Open Tutor Opp
                    }
                }*/
            }
            
            //Create list of accounts, then add map to that list
            List<Contact> ListContacts = MapContacts.values();
            IF(SetContactID.size()>0){
                update ListContacts;
            }
        }
        
        ///////////////////////////////////////////////////////Accounts
        if(setAccountID.size()>0){
            Map<Id,Account> mapAccounts = new Map<Id,Account> (
            [SELECT Id, Books_Adopted__c
            FROM Account WHERE Id IN :setAccountID FOR UPDATE]);
            
            //Set account fields to default
            for(Id accountId : mapAccounts.keySet() ){
                mapAccounts.get(accountId).Books_Adopted__c	= '' ;
            }
            //System.debug('mapAccounts: '+mapAccounts);
            
            List<Opportunity> allOpps = [SELECT Id, Book_Text__c, AccountId
            FROM Opportunity
            WHERE AccountId IN :setAccountID AND IsWon = TRUE
            LIMIT 10000];
            //System.debug('allOpps: '+ allOpps);
            
            for(Opportunity opp: allOpps){
                if(mapAccounts.containsKey(opp.AccountId)){
                    mapAccounts.get(opp.AccountId).Books_Adopted__c = mapAccounts.get(opp.AccountId).Books_Adopted__c+(mapAccounts.get(opp.AccountId).Books_Adopted__c.contains(opp.Book_Text__c)?'': (mapAccounts.get(opp.AccountId).Books_Adopted__c == '' ? '': ', ') + opp.Book_Text__c);
                    String booksAdopted = mapAccounts.get(opp.AccountId).Books_Adopted__c;
                    if(booksAdopted.length() > 255 ){
                        mapAccounts.get(opp.AccountId).Books_Adopted__c = booksAdopted.substring(0, 255);
                    }
                }
            }
            
            //List<Account> listAccounts = mapAccounts.values();
            if(mapAccounts.values().size() > 0){
                update mapAccounts.values();
            }
        }
        /////////////////////////////////////////////Department things
        if(depts.size() > 0){
            List<String> deptKeys = new List<String>();
            Map<String,Opportunity> deptMap = new Map<String,Opportunity>();
            
            for(Opportunity dept: depts){
                deptKeys.add(dept.DeptSort__c);
                dept.Fall_Students__c = (dept.Fall_Dept_Max_Students__c   != null? dept.Fall_Dept_Max_Students__c  : 0);
                dept.Fall_Dept_Max_Students__c = (dept.Fall_Dept_Max_Students__c   != null? dept.Fall_Dept_Max_Students__c  : 0);
                dept.Spring_Students__c = (dept.Spring_Dept_Max_Students__c != null? dept.Spring_Dept_Max_Students__c: 0);
                dept.Spring_Dept_Max_Students__c = (dept.Spring_Dept_Max_Students__c   != null? dept.Spring_Dept_Max_Students__c  : 0);
                dept.Summer_Students__c = (dept.Summer_Dept_Max_Students__c != null? dept.Summer_Dept_Max_Students__c: 0);
                deptMap.put(dept.DeptSort__c,dept);
            }
            //System.debug('deptMap: '+deptMap);
            
            List<Opportunity> subOpps = [SELECT Id, sort__c, Fall_Students__c, Spring_Students__c, Summer_Students__c,
                Opportunity_Record_Type_Name__c, DeptSort__c
            FROM Opportunity
            WHERE DeptSort__c IN :deptKeys AND IsWon = TRUE AND Department_Adoption__c = FALSE
            LIMIT 10000];
            //System.debug('SubOpps: '+subOpps);
            
            if(subOpps.size() > 0){
                for(Opportunity opp: subOpps){
                    if(opp.Opportunity_Record_Type_Name__c == 'Book Opp'){
                        //System.debug('Opp loop: '+opp);
                        //System.debug('opp.DeptSort__c.Fall_Dept_Max_Students__c: '+ deptMap.get(opp.DeptSort__c).Fall_Dept_Max_Students__c);
                        deptMap.get(opp.DeptSort__c).Fall_Students__c = Math.max(deptMap.get(opp.DeptSort__c).Fall_Dept_Max_Students__c - (opp.Fall_Students__c   != null ? opp.Fall_Students__c  :0), 0);
                        deptMap.get(opp.DeptSort__c).Spring_Students__c = Math.max(deptMap.get(opp.DeptSort__c).Spring_Dept_Max_Students__c - (opp.Spring_Students__c != null ? opp.Spring_Students__c:0), 0);
                        //DeptMap.get(Opp.DeptSort__c).Summer_Students__c = math.max(DeptMap.get(Opp.DeptSort__c).Summer_Dept_Max_Students__c - (Opp.Summer_Students__c != null ? Opp.Summer_Students__c:0), 0);
                    }
                }
            }
            List<Opportunity> listOpps = deptMap.values();
            //System.debug('ListOpps: '+listOpps);
            update listOpps;
            //update deptMap.values();
        }
        
        if(normalOppsUpdate.size()>0){
            update normalOppsUpdate;
        }
        if(deptsNeedRollup.size()>0){
            update deptsNeedRollup;
        }
        
        //System.debug('End OppRollup');
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    
    }
    
    public static Boolean duplicateDeptOpportunity(Opportunity oppToLookFor, List<Opportunity> deptsToUpdate){
        Boolean dupFound = false;
        for(Opportunity opp: deptsToUpdate){
            if(opp.Id == oppToLookFor.Department_Opportunity__c){
                //System.debug('Duplicate found: ' + opp.Id);
                dupFound = true;
                break;
            }
        }
        return dupFound;
    }
}