unpackaged/main/default/objects/Account/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Exclude__c.field-meta.xml
<CustomField>
    <fullName>Exclude__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude (testing accounts)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Groups that provide a service alongside our products</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/CountryContinent__c/CountryContinent__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryContinent</label>
</CustomObject>

unpackaged/main/default/objects/CountryContinent__c/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Instant_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Instant_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to true will cause the lead to be converted immediately</description>
    <inlineHelpText>Check to instantly convert to contact</inlineHelpText>
    <label>Instant Conversion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Partner_selected_on_marketplace_form__c.field-meta.xml
<CustomField>
    <fullName>Partner_selected_on_marketplace_form__c</fullName>
    <label>Partner selected on marketplace form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/Partner_Product__c.object-meta.xml
<CustomObject>
    <description>Products that faculty can use</description>
    <label>Partner Product</label>
    <nameField>
        <displayFormat>Partner Product {00000}</displayFormat>
        <label>Partner Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Products</relationshipLabel>
    <relationshipName>Partner_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Partner Products</relationshipLabel>
    <relationshipName>Partner_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LeadConversionTest.cls
@isTest 
public class LeadConversionTest {
    //When the lead conversion actually runs, it makes the log so long that it can't be seen in debug mode, 
    //so you need to change log levels in the debug  menu above
    
    
    public static TestMethod void PartnerProductSwapTest(){
        //This test checks that a partner product assigned to a lead gets updated properly
        Lead l = CreateTestRecords('PartnerProduct');
        
        List<Contact> contacts = [SELECT ID, Partner_selected_on_marketplace_form__c FROM Contact];
        system.debug('contacts: '+contacts);
        
        List<Partner_Product__c> PPs = [SELECT ID, Contact__c, Lead__c FROM Partner_Product__c WHERE Contact__c = :contacts[0].ID ];
        system.debug('PPs: '+PPs);
        system.assert(PPs.size()> 0);
        
    }
    
    static Lead CreateTestRecords(String TestType){
        system.debug('TestType: '+TestType);      
        
        Lead l = new Lead();
        l.FirstName 			= 'Denver';
        l.LastName 				= 'Greene519549519';
        l.Email 				= 'denver+test345753683457345@rice.edu';
        l.Company				= 'Test University';
        
		IF(TestType == 'PartnerProduct'){
            Account NewPartner = new Account();
            NewPartner.Name = 'PartnerTest';
            NewPartner.Type = 'Partner';
            NewPartner.RecordTypeId = [SELECT ID FROM RecordType WHERE Name = 'Partner' AND sObjectType = 'Account'].ID;
            insert NewPartner;
            
            CountryContinent__c CC = new CountryContinent__c();
            CC.Name = 'United States';
            CC.Continent__c = 'North America';
            insert CC;
            
            Account NewAccount = new Account();
            NewAccount.Name = 'Find Me A Home';
            NewAccount.Type = 'Other';
            NewAccount.Exclude__c = TRUE;
            NewAccount.BillingCountry = 'United States';
            NewAccount.Continent__c = 'North America';
            insert NewAccount;
            
            l.Partner_selected_on_marketplace_form__c = 'PartnerTest';
            l.School__c = NewAccount.Id;
            l.Instant_Conversion__c = TRUE;
        }

        system.debug('before insert');
        insert l;
        system.debug('after insert');
        
        return l;
        
      
    }
}