unpackaged/main/default/objects/Account/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Exclude__c.field-meta.xml
<CustomField>
    <fullName>Exclude__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude (testing accounts)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Groups that provide a service alongside our products</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>Colleges, Universities, High Schools</description>
    <label>School</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Accounts_UUID__c.field-meta.xml
<CustomField>
    <fullName>Accounts_UUID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>ID used in OS Accounts</inlineHelpText>
    <label>Accounts UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/AdoptionsJSON__c.field-meta.xml
<CustomField>
    <fullName>AdoptionsJSON__c</fullName>
    <label>AdoptionsJSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Faculty_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Confirmed_Date__c</fullName>
    <description>The Date that Faculty was verified</description>
    <inlineHelpText>Date faculty status was confirmed</inlineHelpText>
    <label>Faculty Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FV_Status__c.field-meta.xml
<CustomField>
    <fullName>FV_Status__c</fullName>
    <label>FV Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FV_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Last_In_Touch_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_In_Touch_Date__c</fullName>
    <inlineHelpText>Most recent date the contact was in touch with us</inlineHelpText>
    <label>Last In Touch Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Faculty.recordType-meta.xml
<RecordType>
    <fullName>Faculty</fullName>
    <active>true</active>
    <label>Faculty</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Lead/fields/Accounts_UUID__c.field-meta.xml
<CustomField>
    <fullName>Accounts_UUID__c</fullName>
    <description>Users OpenStax Accounts UUID. The unique identifier across all OpenStax systems after the user has created an account with us.</description>
    <externalId>true</externalId>
    <label>Accounts_UUID__c</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/AdoptionsJSON__c.field-meta.xml
<CustomField>
    <fullName>AdoptionsJSON__c</fullName>
    <description>This is only populated when someone says they have adopted something</description>
    <label>AdoptionsJSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Application_Source__c.field-meta.xml
<CustomField>
    <fullName>Application_Source__c</fullName>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tutor Signup</fullName>
            </value>
            <value>
                <fullName>OS Web</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Formsite</fullName>
            </value>
            <value>
                <fullName>Zapier</fullName>
            </value>
            <value>
                <fullName>OS Web/Accounts</fullName>
                <isActive>false</isActive>
                <label>OS Web/Accounts</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/FV_Status__c.field-meta.xml
<CustomField>
    <fullName>FV_Status__c</fullName>
    <label>FV Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>incomplete_signup</fullName>
                <label>Incomplete Signup</label>
            </value>
            <value>
                <fullName>rejected_by_sheer_id</fullName>
                <label>Rejected by SheerID</label>
            </value>
            <value>
                <fullName>pending_faculty</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>rejected_faculty</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>confirmed_faculty</fullName>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>no_faculty_info</fullName>
                <label>No Faculty Info</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Instant_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Instant_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to true will cause the lead to be converted immediately</description>
    <inlineHelpText>Check to instantly convert to contact</inlineHelpText>
    <label>Instant Conversion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Partner_selected_on_marketplace_form__c.field-meta.xml
<CustomField>
    <fullName>Partner_selected_on_marketplace_form__c</fullName>
    <label>Partner selected on marketplace form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/Partner_Product__c.object-meta.xml
<CustomObject>
    <description>Products that faculty can use</description>
    <label>Partner Product</label>
    <nameField>
        <displayFormat>Partner Product {00000}</displayFormat>
        <label>Partner Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Products</relationshipLabel>
    <relationshipName>Partner_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Partner Products</relationshipLabel>
    <relationshipName>Partner_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/FV_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>no_faculty_info</fullName>
        <label>No Faculty Info</label>
    </customValue>
    <customValue>
        <fullName>incomplete_signup</fullName>
        <label>Incomplete Signup</label>
    </customValue>
    <customValue>
        <fullName>pending_faculty</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>rejected_by_sheerid</fullName>
        <label>Rejected by SheerID</label>
    </customValue>
    <customValue>
        <fullName>rejected_faculty</fullName>
        <label>Rejected</label>
    </customValue>
    <customValue>
        <fullName>confirmed_faculty</fullName>
        <label>Confirmed</label>
    </customValue>
    <masterLabel>FV Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadConversion.cls
public class LeadConversion { 
    
    public class ConvertInput {
        @InvocableVariable
        public string LeadInput; //(required=true)
    }
    static string leadID;
    
    @InvocableMethod(label='Lead Conversion')
    public static void LeadConversion(List<ConvertInput> inputsMultiple) {
        system.debug('Leads passed in through invoke');
        Set<String> LeadIDs	= new Set<String>();
        for (ConvertInput input : inputsMultiple) {
            LeadIDs.add(input.LeadInput);
        }
        
        List<Lead> LeadList = [SELECT Id, 
                               Name, 
                               Accounts_UUID__c,
                               Role__c, 
                               School__c, 
                               FV_Status__c, 
                               AdoptionsJSON__c,
                               Instant_Conversion__c,
                               Application_Source__c,
                               Company, 
                               Partner_selected_on_marketplace_form__c,
                               Title 
                               FROM Lead 
                               WHERE ID IN :leadIDs AND IsConverted = False ];
        
        //system.debug('LeadList: '+LeadList);
        actualexecute(LeadList, LeadIDs);
    }
    
    public static void actualexecute(List<Lead> Leads, Set<String> LeadIDs){
        system.debug('execute changes - lead conversion');

        //Contact list for updating witah custom values
        List<Contact> ContactList = new List<Contact>();
        
        //get proper date format for description string
        String properDateFormat = String.Valueof(date.today().year()) + '-' + String.Valueof(date.today().month()) + '-' + String.Valueof(date.today().day()) + ', ';
        
        //Get The default school ID for if there is no account found on lead
        List<Account> TheLostSchool = [SELECT ID FROM Account WHERE Name = 'Find Me A Home'];
        String FindMeAHome; 
        IF(TheLostSchool.size() > 0){
            FindMeAHome = TheLostSchool[0].ID;
        }
        ELSE{
            Account NewAccount = new Account();
            NewAccount.Name = 'Find Me A Home';
            NewAccount.Type = 'Other';
            NewAccount.BillingCountry = 'United States';
            NewAccount.Exclude__c = TRUE;
            insert NewAccount;
            FindMeAHome = NewAccount.ID;
        }
        
        List<Partner_Product__c> PPsUpdate = new List<Partner_Product__c>();
        
        for(Lead l : Leads){
            //Set values in the leadConvert method
            String Company;
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(l.Id);
            lc.setConvertedStatus('Converted');
            lc.setDoNotCreateOpportunity(TRUE); 
            
            IF(l.School__c != null){     //sets account ID so a duplicate isn't created
                lc.accountid = l.School__c;
            }
            ELSE { 
                system.debug('use the  find me a home id: '+FindMeAHome);
                lc.accountid = FindMeAHome;
                Company = l.Company;
            }
            
            //Convert the lead using standard  values
            system.debug('before convert');

            Database.LeadConvertResult lcr = Database.convertLead(lc, true);
            
            Contact c = [SELECT ID, AccountID FROM Contact WHERE ID = :lcr.getContactId()];
            system.debug('contact school: '+c.AccountId);
            Account a = [SELECT ID, ShippingAddress, Continent__c FROM Account WHERE ID = :c.AccountId];
            system.debug('account: '+a);

            system.debug('after convert');
            
            if (lcr.isSuccess()) {
                //Custom fields for lead conversion
                string reason = getReason(l);
                Contact con 				= new Contact();
                con.Id						= lcr.getContactId();
                con.Title					= l.Title;
                con.Description				= properDateFormat + UserInfo.getName() + ' - ' + reason + ' - ' + Company;
                IF(l.FV_Status__c == 'confirmed_faculty'){
                    con.Faculty_Confirmed_Date__c = date.today();
                    con.Last_In_Touch_Date__c	= date.today();
                }
                
                ContactList.add(con);
                
                //Check for partner products related to the lead updated
                
                IF(l.Partner_selected_on_marketplace_form__c != null){
                    List<Partner_Product__c> PPs = [SELECT ID, Lead__c, Contact__c
                                                    FROM Partner_Product__c
                                                    WHERE Lead__c IN :LeadIDs];
                   
                    for(Partner_Product__c PP: PPs){
                        IF(PP.Lead__c == l.ID){
                            PP.Contact__c = con.id;
                            PPsUpdate.add(PP);
                        }
                    }
                }
            }
        }

        //contact update
        system.debug('Converted Contacts: '+ContactList);
        try {
            IF(ContactList.size() >0 ){
                update ContactList;
                
                IF(PPsUpdate.size() >0){
                    update PPsUpdate;
                }
            }
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
    }
    
    public static String getReason(Lead l){
        String reason = 'Converted for the following reason(s): ';
        IF(l.FV_Status__c == 'confirmed_faculty'){
            reason += 'Faculty Confirmed, ';
        }
        IF(l.AdoptionsJSON__c != null){
            reason += 'Adoption Confirmed, ';
        }
        IF(l.Accounts_UUID__c != null && l.Role__c == 'Instructor' && l.Application_Source__c == 'Accounts' && l.FV_Status__c != 'Rejected'){
            reason += 'Account Created';
        }
        IF(l.Instant_Conversion__c == TRUE){
            reason += 'Instant Conversion Checkbox';
        }
        return reason;
    }

}