unpackaged/main/default/objects/Account/fields/Email_for_Leads__c.field-meta.xml
<CustomField>
    <fullName>Email_for_Leads__c</fullName>
    <inlineHelpText>use ; to add multiple</inlineHelpText>
    <label>Email for Leads</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Lead_Email_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Email_Frequency__c</fullName>
    <label>Lead Email Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Once a Day</fullName>
            </value>
            <value>
                <fullName>Once a Week</fullName>
                <default>true</default>
                <label>Once a Week</label>
            </value>
            <value>
                <fullName>Once a Month</fullName>
            </value>
            <value>
                <fullName>Never</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Partner__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Groups that provide a service alongside our products</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>Colleges, Universities, High Schools</description>
    <label>School</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Partner__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <inlineHelpText>List of subjects the contact is interested in</inlineHelpText>
    <label>Subject</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Algebra and Trigonometry</fullName>
            </value>
            <value>
                <fullName>American Government</fullName>
            </value>
            <value>
                <fullName>Anatomy &amp; Physiology</fullName>
            </value>
            <value>
                <fullName>Anthropology</fullName>
            </value>
            <value>
                <fullName>AP Bio</fullName>
            </value>
            <value>
                <fullName>AP Macro Econ</fullName>
            </value>
            <value>
                <fullName>AP Micro Econ</fullName>
            </value>
            <value>
                <fullName>AP Physics</fullName>
            </value>
            <value>
                <fullName>Astronomy</fullName>
            </value>
            <value>
                <fullName>Basic College Math</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Business Ethics</fullName>
            </value>
            <value>
                <fullName>Business Law I Essentials</fullName>
            </value>
            <value>
                <fullName>Business Statistics</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Career Readiness</fullName>
            </value>
            <value>
                <fullName>Chem: Atoms First</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>College Algebra</fullName>
            </value>
            <value>
                <fullName>College Algebra with Corequisite Support</fullName>
            </value>
            <value>
                <fullName>College Physics (Algebra)</fullName>
            </value>
            <value>
                <fullName>College Success</fullName>
            </value>
            <value>
                <fullName>Concepts of Bio (non-majors)</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Elementary Algebra</fullName>
            </value>
            <value>
                <fullName>Entrepreneurship</fullName>
            </value>
            <value>
                <fullName>Financial Accounting</fullName>
            </value>
            <value>
                <fullName>Finite Algebra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner__c/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Partner__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Partner_Product__c/Partner_Product__c.object-meta.xml
<CustomObject>
    <description>Products that faculty can use</description>
    <label>Partner Product</label>
    <nameField>
        <displayFormat>Partner Product {00000}</displayFormat>
        <label>Partner Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Products</relationshipLabel>
    <relationshipName>Partner_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <description>Which partner is being used.</description>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Products</relationshipLabel>
    <relationshipName>Partner_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Permission_To_Share__c.field-meta.xml
<CustomField>
    <fullName>Permission_To_Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permission To Share</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Expressed Interest</fullName>
            </value>
            <value>
                <fullName>Using Partner</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Past</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Partner_Product__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Books</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Books.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algebra and Trigonometry</fullName>
    </customValue>
    <customValue>
        <fullName>American Government</fullName>
    </customValue>
    <customValue>
        <fullName>Anatomy &amp; Physiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>AP Bio</fullName>
    </customValue>
    <customValue>
        <fullName>AP Macro Econ</fullName>
    </customValue>
    <customValue>
        <fullName>AP Micro Econ</fullName>
    </customValue>
    <customValue>
        <fullName>AP Physics</fullName>
    </customValue>
    <customValue>
        <fullName>Astronomy</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business Ethics</fullName>
    </customValue>
    <customValue>
        <fullName>Business Law I Essentials</fullName>
    </customValue>
    <customValue>
        <fullName>Business Statistics</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus</fullName>
    </customValue>
    <customValue>
        <fullName>Chem: Atoms First</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>College Algebra</fullName>
    </customValue>
    <customValue>
        <fullName>College Algebra with Corequisite Support</fullName>
    </customValue>
    <customValue>
        <fullName>College Physics (Algebra)</fullName>
    </customValue>
    <customValue>
        <fullName>College Success</fullName>
    </customValue>
    <customValue>
        <fullName>Concepts of Bio (non-majors)</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Math</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary Algebra</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Física universitaria</fullName>
    </customValue>
    <customValue>
        <fullName>HS Physics</fullName>
    </customValue>
    <customValue>
        <fullName>HS Statistics</fullName>
    </customValue>
    <customValue>
        <fullName>Intellectual Property</fullName>
    </customValue>
    <description>A global list of the books we offer and should be used when referencing them.</description>
    <masterLabel>Books</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Partner_Reminder_Email_Test.cls
@isTest
public class Partner_Reminder_Email_Test {
	public static TestMethod void testthethings(){
    	/*system.debug('Start Partner email Test');
    
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get('Partner').getRecordTypeId();
        
        //Create Partners
        List<Account> newPartners = new List<Account>();
        Account a1 	= new Account();
        a1.Name 	= 'School Partner test 11111';
        a1.recordTypeId = recordTypeId;
        a1.Type		= 'Adaptive Courseware Partners ';
        a1.Phone	= '0000000000';
        a1.Website	= 'website.com';
        a1.Lead_Email_Frequency__c = 'Once a Day';
        a1.Email_for_Leads__c = 'denver+test1@rice.edu, denver+test4@rice.edu';
        newPartners.add(a1);
        
        Account a2 	= new Account();
        a2.Name 	= 'School Partner test 22222';
        a2.recordTypeId = recordTypeId;
        a2.Type		= 'Adaptive Courseware ';
        a2.Phone	= '0000000000';
        a2.Website	= 'website.com';
        a2.Lead_Email_Frequency__c = 'Once a Week';
        a2.Email_for_Leads__c = 'denver+test2@rice.edu';
        newPartners.add(a2);
        
        Account a3 	= new Account();
        a3.Name 	= 'School Partner test 33333';
        a3.recordTypeId = recordTypeId;
        a3.Type		= 'Adaptive Courseware ';
        a3.Phone	= '0000000000';
        a3.Website	= 'website.com';
        a3.Lead_Email_Frequency__c = 'Once a Month';
        a3.Email_for_Leads__c = 'denver+test3@rice.edu';
        newPartners.add(a3);
        insert newPartners;
        
        
        //Create Contact
        Contact c1 		= new Contact();
        c1.FirstName	= 'Denver';
        c1.LastName		= 'Greene1';
        c1.AccountId 	= a1.Id;
        c1.Phone		= '0000000000';
        c1.Email		= 'denver+test1@rice.edu';
        c1.Subject__c	= 'Biology';
        insert c1;
        
        Contact c4 		= new Contact();
        c4.FirstName	= 'Denver';
        c4.LastName		= 'Greene4';
        c4.AccountId 	= a1.Id;
        c4.Phone		= '0000000000';
        c4.Email		= 'denver+test4@rice.edu';
        c4.Subject__c	= 'Biology';
        insert c4;
        
        Contact c2 		= new Contact();
        c2.FirstName	= 'Denver';
        c2.LastName		= 'Greene2';
        c2.AccountId 	= a2.Id;
        c2.Phone		= '0000000000';
        c2.Email		= 'denver+test2@rice.edu';
        c2.Subject__c	= 'Biology';
        insert c2;
        
        Contact c3 		= new Contact();
        c3.FirstName	= 'Denver';
        c3.LastName		= 'Greene3';
        c3.AccountId 	= a3.Id;
        c3.Phone		= '0000000000';
        c3.Email		= 'denver+test3@rice.edu';
        c3.Subject__c	= 'Biology';
        insert c3;
        
        //Create Partner Product
        List<Partner_Product__c> PPs = new List<Partner_Product__c>();
        Partner_Product__c PP1 = new Partner_Product__c();
        PP1.Partner__c = a1.id;
        PP1.Contact__c = c1.id;
        PP1.Permission_To_Share__c = TRUE;
        PP1.Stage__c = 'Expressed Interest';
        PPs.add(pp1);
        
        Partner_Product__c PP2 = new Partner_Product__c();
        PP2.Partner__c = a2.id;
        PP2.Contact__c = c2.id;
        PP2.Permission_To_Share__c = TRUE;
        PP2.Stage__c = 'Expressed Interest';
        PPs.add(pp2);
        
        Partner_Product__c PP3 = new Partner_Product__c();
        PP3.Partner__c = a3.id;
        PP3.Contact__c = c3.id;
        PP3.Permission_To_Share__c = TRUE;
        PP3.Stage__c = 'Expressed Interest';
        PPs.add(pp3);
        
        insert PPs;
        
        Date ThisDate 	 = Date.newInstance(2019, 10, 1);
        Date OneMonthAgo = ThisDate.addMonths(-1);
        Date OneWeekAgo	 = ThisDate-7;
        Date Yesterday   = ThisDate-1;
        
        Test.setCreatedDate(PP1.Id, yesterday); 
        Test.setCreatedDate(PP2.Id, OneWeekAgo); 
        Test.setCreatedDate(PP3.Id, OneMonthAgo); 
        
        list<Date> inputDateList = new List<date>{ThisDate};
        Partner_Reminder_Email.PartnerEmail(inputDateList);
        Integer invocations = Limits.getEmailInvocations();
        system.debug('Number of emails sent: '+invocations);
        system.assert(invocations == 4);
        
        Test.setCreatedDate(PP1.Id, yesterday+1); 
        
        list<Date> inputDateList2 = new List<date>{ThisDate+1};
        Partner_Reminder_Email.PartnerEmail(inputDateList2);
        invocations = Limits.getEmailInvocations();
        system.debug('Number of emails sent: '+invocations);
        system.assert(invocations == 6);
*/
    }
}