unpackaged/main/default/objects/Account/fields/IPEDS_ID__c.field-meta.xml
<CustomField>
    <fullName>IPEDS_ID__c</fullName>
    <externalId>true</externalId>
    <label>IPEDS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>Colleges, Universities, High Schools</description>
    <label>School</label>
</RecordType>

unpackaged/main/default/objects/Batch_Size__mdt/Batch_Size__mdt.object-meta.xml
<CustomObject>
    <label>Batch Size</label>
    <pluralLabel>Batch Sizes</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Batch_Size__mdt/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>BatchSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BMG__c/BMG__c.object-meta.xml
<CustomObject>
    <label>BMG</label>
    <nameField>
        <label>BMG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BMGs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BMG__c/fields/Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Book_Name__c</fullName>
    <label>Book Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BMG__c/fields/Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Enrollments__c</fullName>
    <label>Enrollments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BMG__c/fields/IPED__c.field-meta.xml
<CustomField>
    <fullName>IPED__c</fullName>
    <label>IPED</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BMG__c/fields/Needs_Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>Needs_Manual_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BMG__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BMG__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>VALUE(RIGHT( Period__c , 4)) -IF( LEFT( Period__c , 4) = "Spri",1,0)+
IF( LEFT( Period__c , 4) = "Spri",0.2,0.1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>OpenStax College book offerings</description>
    <label>Book</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Books</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/All_Emails__c.field-meta.xml
<CustomField>
    <fullName>All_Emails__c</fullName>
    <description>All emails associated with this contact. Populated from leads and from</description>
    <externalId>true</externalId>
    <inlineHelpText>All emails associated with contact</inlineHelpText>
    <label>All Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Last_In_Touch_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_In_Touch_Date__c</fullName>
    <inlineHelpText>Most recent date the contact was in touch with us</inlineHelpText>
    <label>Last In Touch Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Skip_Flow__c.field-meta.xml
<CustomField>
    <fullName>Skip_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Not used - helped with automation</inlineHelpText>
    <label>Skip Flow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <inlineHelpText>List of subjects the contact is interested in</inlineHelpText>
    <label>Subject</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Algebra and Trigonometry</fullName>
            </value>
            <value>
                <fullName>American Government</fullName>
            </value>
            <value>
                <fullName>Anatomy &amp; Physiology</fullName>
            </value>
            <value>
                <fullName>Anthropology</fullName>
            </value>
            <value>
                <fullName>AP Bio</fullName>
            </value>
            <value>
                <fullName>AP Macro Econ</fullName>
            </value>
            <value>
                <fullName>AP Micro Econ</fullName>
            </value>
            <value>
                <fullName>AP Physics</fullName>
            </value>
            <value>
                <fullName>Astronomy</fullName>
            </value>
            <value>
                <fullName>Basic College Math</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Business Ethics</fullName>
            </value>
            <value>
                <fullName>Business Law I Essentials</fullName>
            </value>
            <value>
                <fullName>Business Statistics</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Career Readiness</fullName>
            </value>
            <value>
                <fullName>Chem: Atoms First</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>College Algebra</fullName>
            </value>
            <value>
                <fullName>College Algebra with Corequisite Support</fullName>
            </value>
            <value>
                <fullName>College Physics (Algebra)</fullName>
            </value>
            <value>
                <fullName>College Success</fullName>
            </value>
            <value>
                <fullName>Concepts of Bio (non-majors)</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Elementary Algebra</fullName>
            </value>
            <value>
                <fullName>Entrepreneurship</fullName>
            </value>
            <value>
                <fullName>Financial Accounting</fullName>
            </value>
            <value>
                <fullName>Finite Algebra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/All_Emails__c.field-meta.xml
<CustomField>
    <fullName>All_Emails__c</fullName>
    <formula>Contact__r.All_Emails__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>All Emails</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Base_Year__c.field-meta.xml
<CustomField>
    <fullName>Base_Year__c</fullName>
    <formula>year( Class_Start_Date__c )- 

IF(Month(Class_Start_Date__c) &gt;6, 
   0, 
   1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Class_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Class_Start_Date__c</fullName>
    <label>Class Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/First__c.field-meta.xml
<CustomField>
    <fullName>First__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_In_Touch_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_In_Touch_Date__c</fullName>
    <formula>Contact__r.Last_In_Touch_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last In Touch Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Need_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Need_Rollup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Rollup</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Status__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Status__c</fullName>
    <label>Renewal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs Renewal</fullName>
                <default>true</default>
                <label>Needs Renewal</label>
            </value>
            <value>
                <fullName>Done Renewed</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>Needs check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Skip_Flow__c.field-meta.xml
<CustomField>
    <fullName>Skip_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Flow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Student_No_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_No_Status__c</fullName>
    <label>Student No Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Auto-Guess</fullName>
            </value>
            <value>
                <fullName>Annualized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Students__c.field-meta.xml
<CustomField>
    <fullName>Students__c</fullName>
    <label>Students</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Time_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Period__c</fullName>
    <label>Time Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semester</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <description>This field is used for catching duplicates. Because the Opportunity is recreated every year it needs to account for that, and this is how.</description>
    <formula>TEXT(
IF(Month(Class_Start_Date__c )&lt;7, 
Year(Class_Start_Date__c)-1, 
Year( Class_Start_Date__c )) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>year</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Books.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algebra and Trigonometry</fullName>
    </customValue>
    <customValue>
        <fullName>American Government</fullName>
    </customValue>
    <customValue>
        <fullName>Anatomy &amp; Physiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>AP Bio</fullName>
    </customValue>
    <customValue>
        <fullName>AP Macro Econ</fullName>
    </customValue>
    <customValue>
        <fullName>AP Micro Econ</fullName>
    </customValue>
    <customValue>
        <fullName>AP Physics</fullName>
    </customValue>
    <customValue>
        <fullName>Astronomy</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business Ethics</fullName>
    </customValue>
    <customValue>
        <fullName>Business Law I Essentials</fullName>
    </customValue>
    <customValue>
        <fullName>Business Statistics</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus</fullName>
    </customValue>
    <customValue>
        <fullName>Chem: Atoms First</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>College Algebra</fullName>
    </customValue>
    <customValue>
        <fullName>College Algebra with Corequisite Support</fullName>
    </customValue>
    <customValue>
        <fullName>College Physics (Algebra)</fullName>
    </customValue>
    <customValue>
        <fullName>College Success</fullName>
    </customValue>
    <customValue>
        <fullName>Concepts of Bio (non-majors)</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Math</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary Algebra</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Física universitaria</fullName>
    </customValue>
    <customValue>
        <fullName>HS Physics</fullName>
    </customValue>
    <customValue>
        <fullName>HS Statistics</fullName>
    </customValue>
    <customValue>
        <fullName>Intellectual Property</fullName>
    </customValue>
    <description>A global list of the books we offer and should be used when referencing them.</description>
    <masterLabel>Books</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FileUploader.cls
global class FileUploader implements Database.Batchable<sObject> //,Schedulable 
{
    //this top section is if we want it to be schedulable, but I don't think we do, but I don't want to delete it 
    /*global static void execute(SchedulableContext SC){
        List<BMG__c> BMGs = [SELECT Book_Name__c, IPED__c, Period__c, Enrollments__c, First_Name__c, Last_Name__c, Email__c, Year__c
                             FROM BMG__c
                             WHERE Needs_Manual_Entry__c = FALSE
                             ORDER BY Year__c
                             LIMIT 350//:batchSize
                            ];
        ReadBMG(BMGs);
}*/
    
    //Creates a query for gathering records
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            'SELECT Book_Name__c, IPED__c, Period__c, Enrollments__c, First_Name__c, '
            + 'Last_Name__c, Email__c, Year__c '
            + 'FROM BMG__c '
            + 'WHERE Needs_Manual_Entry__c = FALSE '
            + 'ORDER BY Year__c'
        );
    }
    
    //runs the records from above through some code listed below
    public void execute(Database.BatchableContext bc, List<BMG__c> BMGs){
      //  ReadBMG(BMGs);
    }
    
    @invocableMethod
    public static void ReadBMG(List<BMG__c> BMGs){
    /*    system.debug('Start Method');
        
        //Get and make variables/maps
        //other
        Integer batchSize = Integer.valueOf([SELECT BatchSize__c FROM Batch_Size__mdt WHERE Label = 'BMGBatch' LIMIT 1].BatchSize__c);
        Set<String> SetAccountIPEDs = new Set<String>();
        Set<String> SetEmails		= new Set<String>();
        Set<ID> SetContactIDs		= new Set<ID>();
        Set<String> SetContactName	= new Set<String>();
        
        //BMGs
        List<BMG__c> bmgUpdate = new List<BMG__c>();
        List<BMG__c> bmgDelete = new List<BMG__c>();
        for(BMG__c BMG : BMGs){
            SetAccountIPEDs.add(BMG.IPED__c);
            SetEmails.add('%'+BMG.Email__c+'%');
            SetContactName.add(BMG.First_Name__c+' '+BMG.Last_Name__c);
        }
        
        //Account
        Map<string,Account> schoolMap = new Map<string, Account>();
        Account[] schoolsList = [SELECT ID, IPEDS_ID__c
                 				FROM Account 
                                WHERE IPEDS_ID__c IN :SetAccountIPEDs];
        for(Account a : schoolsList){
            schoolMap.put(a.IPEDS_ID__c,a);
        }
        
        //Contact
        Map<String,Contact> contactEmailMap = new Map<String,Contact>(); //dup check based on email
        Map<String,Contact> contactNameMap	= new Map<String,Contact>(); //dup check based on school name and person name match
        Map<String,Contact> contactsNewMap	= new Map<String,Contact>(); //new contacts to be created
        Map<String,Contact> ContactUpdateMap= new Map<String,Contact>(); //contacts need to be updated
        Map<String,Contact> oppContactMap	= new Map<String,Contact>();
        Contact[] contactList = [SELECT ID, AccountId, All_Emails__c, Email, Name, Subject__c
                 				FROM Contact
                                WHERE All_Emails__c LIKE :SetEmails OR (AccountId IN :schoolsList AND Name IN :SetContactName)];
        for(Contact c : contactList){
            List<String> AllEmails = c.All_Emails__c.split(',');
            for(String email : AllEmails){
                contactEmailMap.put(email.trim(),c);
            }
            IF(!contactEmailMap.containsKey(c.Email)){
                contactEmailMap.put(c.Email,c);
            }
            contactNameMap.put(c.AccountId+c.Name,c);
            SetContactIDs.add(c.id);
        }
        
        //Opportunity
        Map<String,Opportunity> OppMapSort	= new Map<String,Opportunity>(); // for checking exact duplicates
        Map<String,Opportunity> OppMapBSC	= new Map<String,Opportunity>(); // BSC = BookSchoolContact, for checking earlier opps
        Map<String,Opportunity> OppMapDup	= new Map<String,Opportunity>(); //for checking duplicates
        List<Opportunity> OppUpsert 		= new List<Opportunity>(); // for upserting
        String OppRecordTypeID 				= Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Book Opp').getRecordTypeId();
        Opportunity[] OppList = [SELECT ID, Book__c, AccountId, Contact__c, Base_Year__c, Students__c, IsClosed, StageName
                                 FROM Opportunity
                                 WHERE Contact__c IN :SetContactIDs
                                ];
        for(Opportunity o : OppList){ 
            //had to convert to id before string so that it gets the long id insetad of the short one.
            ID Book = o.Book__c;
            ID School = o.AccountId;
            ID Contact = o.Contact__c;
            String BSC = Book+string.valueOf(School) +string.valueOf(Contact);
            OppMapBSC.put(BSC,o);
            
            String oppSort = BSC;
            oppSort += 'FALS';
            oppSort += o.Base_Year__c;
            OppMapSort.put(oppSort, o);
        }
        
        //Books 
        Map<String,Book__c> bookNameMap = new Map<String,Book__c>();
        Book__c[] BookList = [SELECT ID, Name FROM Book__c];
        for(Book__c b: BookList){
            bookNameMap.put(b.Name,b);
        }

        //////loop through rows to check contacts
        try{
            for (BMG__c BMG : BMGs){
                system.debug('New Row.........................................................................................');
                system.debug('BMG: '+BMG);
                
                String Book			= BMG.Book_Name__c;
                String IPED 		= BMG.IPED__c;
                String Period 		= BMG.Period__c;
                integer students 	= Integer.ValueOf(BMG.Enrollments__c);
                String FirstName 	= BMG.First_Name__c;
                String LastName 	= BMG.Last_Name__c;
                String Email 		= BMG.Email__c;
                
                IF(!schoolMap.containsKey(IPED)){
                    //No School
                    BMG.Needs_Manual_Entry__c = TRUE;
                    bmgUpdate.add(BMG);
                    //system.debug('No School, leave for later');
                }
                ELSE IF(ContactUpdateMap.containsKey(Email)){
                    //contact already being updated
                    //system.debug('contact already being updated');
                    List<String> subjects = ContactUpdateMap.get(Email).Subject__c.split(';');
                    IF(!subjects.contains(Book)){
                        ContactUpdateMap.get(Email).Subject__c += '; '+ Book;
                    }
                }
                ELSE IF(contactEmailMap.containsKey(Email) || contactNameMap.containsKey(schoolMap.get(IPED).ID+FirstName+' '+LastName)){
                    //Contact Found, update LIT date
                    //system.debug('Contact Found, update LIT date');
                    Contact con = new Contact();
                    IF(contactEmailMap.containsKey(Email)){ //email match
                        con = contactEmailMap.get(Email);
                        //system.debug('email match');
                    }
                    ELSE IF(contactNameMap.containsKey(schoolMap.get(IPED).ID+FirstName+' '+LastName)){ //name match
                        con = contactNameMap.get(schoolMap.get(IPED).ID+FirstName+' '+LastName);
                        //system.debug('name match');
                    }
                    IF(con != null && !ContactUpdateMap.containsKey(Email)){ //update and add to updateMap
                        system.debug('update contact');
                        con.Last_In_Touch_Date__c = date.newInstance(System.Today().year(), 06, 01);
                        //system.debug('con '+con);
                        IF(con.Subject__c != null){
                            
                            List<String> subjects = con.Subject__c.split(';');
                            IF(!subjects.contains(Book)){
                                con.Subject__c += '; '+ Book;
                            }
                        }
                        ELSE{
                            con.Subject__c = Book;
                        }
                        ContactUpdateMap.put(Email,con);
                        oppContactMap.put(Email,con);
                    }
                }
                ELSE{
                    //No Contact
                    IF(schoolMap.containsKey(IPED)){
                        //School Found
                        IF(contactsNewMap.containsKey(Email)){
                            //Contact already inserted, add subject
                            //system.debug('Contact already inserted, add subject');
                            List<String> subjects = contactsNewMap.get(Email).Subject__c.split(';');
                            IF(!subjects.contains(Book)){
                                contactsNewMap.get(Email).Subject__c += '; '+ Book ;
                            }
                        }
                        ELSE{
                            //New contact will be inserted
                            //system.debug('New contact will be inserted');
                            Contact newContact 		= new Contact();
                            newContact.AccountId 	= schoolMap.get(IPED).id;
                            newContact.FirstName 	= FirstName;
                            newContact.LastName  	= LastName;
                            newContact.Phone		= '0000000000';
                            newContact.Email		= Email;
                            newContact.Subject__c	= Book;
                            newContact.Last_In_Touch_Date__c = date.today();
                            contactsNewMap.put(Email,newContact);
                            oppContactMap.put(Email,newContact);
                        }
                    }
                }
            }
        }
        catch(Exception e){
            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured reading the CSV file'+e.getMessage());
            //system.debug('error: '+errormsg);
        }
        
        //////////Insert/update Contacts
        try{
            List<Contact> ContactInsert = new List<Contact>(contactsNewMap.values());
            insert ContactInsert;
            for(Contact c : ContactInsert){
                contactEmailMap.put(c.Email,c);
            }
            
            List<Contact> ContactUpdate = new List<Contact>(ContactUpdateMap.values());
            update ContactUpdate;
            for(Contact c: ContactUpdate){
                contactEmailMap.put(c.Email,c);
            }
        }
        catch(Exception e){
            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured inserting/updating contacts'+e.getMessage());
            //system.debug('error: '+errormsg);
        }
        
        
        
        //////loop through rows to check opportunities
        system.debug('...............................................................................................................................................Start Opps');
        try{
            for (BMG__c BMG : BMGs){
                system.debug('New Row.........................................................................................');
                
                String Book			= BMG.Book_Name__c;
                String IPED 		= BMG.IPED__c;
                String Period 		= BMG.Period__c;
                integer students 	= Integer.ValueOf(BMG.Enrollments__c);
                String FirstName 	= BMG.First_Name__c;
                String LastName 	= BMG.Last_Name__c;
                String Email 		= BMG.Email__c;
                
                system.debug('BMG: '+BMG);
                
                IF(oppContactMap.containsKey(Email)){
                    //Get Date related fields
                    String Term 		= Period.left(Period.length()-5);
                    Integer month		= (Term == 'Spring' ? 01 : Term == 'Fall' ? 08 :06);
                    Integer Year		= Integer.ValueOf(Period.right(4));
                    Integer BaseYear	= Year - (Term == 'Spring' ? 1 : 0);
                    
                    // this is how to get the sort field on the opp (for duplicate checking)
                    String oppBSC = bookNameMap.get(Book).Id;
                    oppBSC += schoolMap.get(IPED).ID;
                    oppBSC += oppContactMap.get(Email).ID;
                    String oppSort = oppBSC;
                    oppSort += 'FALS';
                    oppSort += BaseYear;
                    
                    //Search for Opps
                    //system.debug('search for opps');
                    IF(OppMapSort.containsKey(oppSort)){
                        //OppFound
                        //system.debug('opp found');
                        IF(OppMapBSC.containsKey(oppBSC) && !OppMapBSC.get(oppBSC).IsClosed){
                            Opportunity oppUpdate 		= OppMapBSC.get(oppBSC);
                            oppUpdate.StageName 		= 'Confirmed Adoption Won';
                            oppUpdate.Renewal_Status__c = 'Needs Renewal';
                            oppUpdate.Need_Rollup__c	= TRUE;
                            oppUpdate.Students__c		= students; 
                            OppUpsert.add(oppUpdate);
                        }
                        ELSE {system.debug('Opp already closed');}
                        bmgDelete.add(BMG);
                    }
                    ELSE IF(OppMapDup.containsKey(oppSort)){
                        //system.debug('Already updated, do nothing');
                        bmgDelete.add(BMG);
                    }
                    ELSE{
                        //Opp Not Found
                        //system.debug('opp not found');
                        Opportunity newOpp 			= new Opportunity();
                        newOpp.AccountId			= schoolMap.get(IPED).Id;
                        newOpp.Book__c				= bookNameMap.get(Book).Id;
                        newOpp.Class_Start_Date__c	= date.newInstance(year, month , 10); 
                        newOpp.CloseDate			= date.today();
                        newOpp.Closer__c			= UserInfo.getUserId();
                        newOpp.Contact__c			= oppContactMap.get(Email).Id;
                        newOpp.Description			= date.today()+', '+UserInfo.getName()+', BMG Import 2021' ; //make sure the date doesn't have time, which seems to be the default
                        newOpp.First__c				= TRUE;
                        newOpp.LeadSource			= 'BMG Import';
                        newOpp.Name					= 'temp';
                        newOpp.Need_Rollup__c		= TRUE;
                        newOpp.RecordTypeId			= OppRecordTypeId;
                        newOpp.StageName			= 'Confirmed Adoption Won';
                        newOpp.Student_No_Status__c	= 'Reported';
                        newOpp.Renewal_Status__c 	= 'Needs Renewal';
                        newOpp.Students__c			= students;
                        newOpp.Time_Period__c		= 'Year';
                        //newOpp.Skip_Flow__c			= TRUE;
                        newOpp.Type					= (OppMapBSC.containsKey(oppBSC) ? 'Renewal' : 'New Business');
                        OppUpsert.add(newOpp);
                        bmgDelete.add(BMG);
                        
                        //system.debug('newOpp: '+newOpp);
                        //add to OppMapDup, in case their csv has duplicates
                        OppMapDup.put(oppSort, newOpp);
                        OppMapBSC.put(oppBSC, newOpp);
                    }
                }
                ELSE{System.debug('No account, so no opp');}
            }
        }
        catch (Exception e){
            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured processing opportunities '+e.getMessage());
            //system.debug('error: '+errormsg);
        }
        
        try{
            //Upserting opportunities
            upsert OppUpsert;
            update bmgUpdate;
            delete bmgDelete;
        }
        catch (Exception e){
            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured upserting opportunities '+e.getMessage());
            //system.debug('error: '+errormsg);
        }
    
        
        system.debug('end method');
        //return null;
      */
    }
        
    
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}