unpackaged/main/default/objects/Opportunity/fields/Base_Year__c.field-meta.xml
<CustomField>
    <fullName>Base_Year__c</fullName>
    <formula>year( Class_Start_Date__c )- 

IF(Month(Class_Start_Date__c) &gt;6, 
   0, 
   1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Status__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Status__c</fullName>
    <label>Renewal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs Renewal</fullName>
                <default>true</default>
                <label>Needs Renewal</label>
            </value>
            <value>
                <fullName>Done Renewed</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>Needs check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Rollover.cls
global class Rollover implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    integer baseyear;
    
    global Rollover(integer passedBaseYear) {
        baseyear = passedBaseYear;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID,Renewal_Status__c '
            + 'FROM Opportunity '
            + 'WHERE Base_Year__c = ' +baseyear
            + ' AND Renewal_Status__c = \'Needs Renewal\' '
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> Opps){
        for(Opportunity opp : Opps){
            Map<String, Object> params = new Map<String, Object>();
            params.put('varOppId',opp.id);
            Flow.Interview.Rollover_Opps_Auto RolloverFlow = new Flow.Interview.Rollover_Opps_Auto(params);
            RolloverFlow.start();
        }
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
        
}