unpackaged/main/default/objects/Opportunity/fields/Need_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Need_Rollup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Rollup</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Status__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Status__c</fullName>
    <label>Renewal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs Renewal</fullName>
                <default>true</default>
                <label>Needs Renewal</label>
            </value>
            <value>
                <fullName>Done Renewed</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>Needs check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Trigger_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Rollup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>bulk processing</description>
    <label>Trigger Rollup</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BulkRollup.cls
global class BulkRollup implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID,Renewal_Status__c '
            + 'FROM Opportunity '
            + 'WHERE Need_Rollup__c = TRUE'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> Opps){
        for(Opportunity opp : Opps){
            opp.Trigger_Rollup__c = TRUE;
        }
        update Opps;
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
    
    
}